// src/components/Elements/ReloadPrompt/ReloadPrompt.tsx
import { useRegisterSW } from 'virtual:pwa-register/react'

const intervalMS = 60 * 60 * 1000

export const ReloadPrompt = () => {
  const {
    offlineReady: [offlineReady, setOfflineReady],
    needRefresh: [needRefresh, setNeedRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    onRegistered(r) {
      r &&
        setInterval(() => {
          r.update()
        }, intervalMS)
    },
    onRegisterError(error) {
      console.log('SW registration error', error)
    },
  })

  const close = () => {
    setOfflineReady(false)
    setNeedRefresh(false)
  }

  return (
    <div className="p-0 m-0 h-0 w-0">
      {(offlineReady || needRefresh) && (
        <div className="fixed right-0 bottom-0 m-4 p-3 border border-gray-100 rounded-md shadow-md bg-gray-900">
          <div className="mb-2">
            {offlineReady ? (
              <span>App ready to work offline</span>
            ) : (
              <span>New content available, click on reload button to update.</span>
            )}
          </div>
          {needRefresh && (
            <button
              className="border border-gray-100 outline-none mr-1 rounded-sm py-1 px-3"
              onClick={() => updateServiceWorker(true)}
            >
              Reload
            </button>
          )}
          <button
            className="border border-gray-100 outline-none mr-1 rounded-sm py-1 px-3"
            onClick={() => close()}
          >
            Close
          </button>
        </div>
      )}
    </div>
  )
}

// src/components/ReloadPrompt.vue
<script setup lang="ts">
import { useUiStore } from '@/store/ui'
import { useRegisterSW } from 'virtual:pwa-register/vue'
const intervalMS = 15 * 60 * 1000

const { offlineReady, needRefresh, updateServiceWorker } = useRegisterSW({
  onRegistered(r) {
    r &&
      setInterval(() => {
        console.log('checking for update')
        r.update()
      }, intervalMS)
  },
})
const close = async () => {
  offlineReady.value = false
  needRefresh.value = false
}

const uiStore = useUiStore()
</script>

<template>
  <div
    v-if="offlineReady || needRefresh"
    class="pwa-toast rounded-lg z-10 fixed bottom-4 right-4 border-1 border-gray-500 shadow-md text-left m-4 p-3"
    :class="[uiStore.tableHeadStyle]"
    role="alert"
  >
    <div class="mb-2">
      <span v-if="offlineReady"> App ready to work offline </span>
      <span v-else>
        New content available, click on reload button to update.
      </span>
    </div>
    <button v-if="needRefresh" @click="updateServiceWorker()"> Reload </button>
    <button @click="close"> Close </button>
  </div>
</template>

<style>
.pwa-toast button {
  border: 1px solid #8885;
  outline: none;
  margin-right: 5px;
  border-radius: 2px;
  padding: 3px 10px;
}
</style>
